# Generated by Django 5.0.3 on 2024-04-03 16:20

import django.db.models.deletion
import django_bunny.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('usadas', models.IntegerField(default=0)),
                ('restantes', models.IntegerField(default=0)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=14)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_nombres', models.CharField(max_length=255)),
                ('datos_apellidos', models.CharField(max_length=255)),
                ('datos_curp', models.CharField(max_length=255)),
                ('datos_sangre', models.CharField(max_length=255)),
                ('datos_sexo', models.CharField(max_length=255)),
                ('datos_nacionalidad', models.CharField(max_length=255)),
                ('datos_restriacciones', models.TextField()),
                ('datos_nacimiento', models.DateField()),
                ('datos_rfc', models.CharField(max_length=255)),
                ('datos_donante', models.BooleanField()),
                ('direc_calle', models.CharField(max_length=255)),
                ('direc_ciudad', models.CharField(max_length=255)),
                ('direc_cp', models.CharField(max_length=255)),
                ('direc_colonia', models.CharField(max_length=255)),
                ('direc_estado', models.CharField(max_length=255)),
                ('lic_expedicion', models.DateField()),
                ('lic_emisora', models.CharField(max_length=255)),
                ('lic_antiguedad', models.DateField()),
                ('lic_tipo', models.CharField(max_length=255)),
                ('lic_valido', models.CharField(blank=True, max_length=255, null=True)),
                ('con_nombre', models.CharField(max_length=255)),
                ('con_apellido', models.CharField(max_length=255)),
                ('con_tel', models.CharField(max_length=255)),
                ('foto_file', models.ImageField(storage=django_bunny.storage.BunnyStorage(), upload_to='fotos/')),
                ('firma_file', models.ImageField(storage=django_bunny.storage.BunnyStorage(), upload_to='firmas/')),
                ('anverso_img', models.ImageField(storage=django_bunny.storage.BunnyStorage(), upload_to='anversos/')),
                ('reverso_img', models.ImageField(storage=django_bunny.storage.BunnyStorage(), upload_to='reversos/')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('folio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='licencias.folio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Licencias',
                'ordering': ['datos_nombres'],
            },
        ),
    ]
