# Generated by Django 4.1.7 on 2023-11-28 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licencia',
            name='lic_valido',
        ),
    ]
