# Generated by Django 4.1.7 on 2023-11-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0002_remove_licencia_lic_valido'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencia',
            name='lic_valido',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
