# Generated by Django 5.0.3 on 2024-04-04 22:48

import django_bunny.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0002_licencia_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencia',
            name='anverso_img',
            field=models.ImageField(blank=True, null=True, storage=django_bunny.storage.BunnyStorage(), upload_to='anversos/'),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='reverso_img',
            field=models.ImageField(blank=True, null=True, storage=django_bunny.storage.BunnyStorage(), upload_to='reversos/'),
        ),
    ]
