# Generated by Django 4.1.7 on 2023-11-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0004_folio_licencia_folio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folio',
            name='texto',
            field=models.CharField(max_length=14),
        ),
    ]
