# Generated by Django 4.1.7 on 2023-11-27 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_nombres', models.CharField(max_length=255)),
                ('datos_apellidos', models.CharField(max_length=255)),
                ('datos_curp', models.CharField(max_length=20)),
                ('datos_sangre', models.CharField(max_length=15)),
                ('datos_sexo', models.CharField(max_length=10)),
                ('datos_nacionalidad', models.CharField(max_length=255)),
                ('datos_restriacciones', models.TextField()),
                ('datos_nacimiento', models.DateField()),
                ('datos_rfc', models.CharField(max_length=13)),
                ('datos_donante', models.BooleanField()),
                ('direc_calle', models.CharField(max_length=255)),
                ('direc_ciudad', models.CharField(max_length=255)),
                ('direc_cp', models.CharField(max_length=5)),
                ('direc_colonia', models.CharField(max_length=255)),
                ('direc_estado', models.CharField(max_length=255)),
                ('lic_expedicion', models.DateField()),
                ('lic_emisora', models.CharField(max_length=255)),
                ('lic_antiguedad', models.DateField()),
                ('lic_tipo', models.CharField(max_length=255)),
                ('lic_valido', models.BooleanField()),
                ('con_nombre', models.CharField(max_length=255)),
                ('con_apellido', models.CharField(max_length=255)),
                ('con_tel', models.CharField(max_length=10)),
                ('foto_file', models.ImageField(upload_to='fotos/')),
                ('firma_file', models.ImageField(upload_to='firmas/')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Licencias',
                'ordering': ['datos_nombres'],
            },
        ),
    ]
