# Generated by Django 4.1.7 on 2023-12-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0006_asignaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaciones',
            name='restantes',
            field=models.IntegerField(default=0),
        ),
    ]
